name: "Fix PHP Code Styling"

on:
  push:
    paths:
      - '**.php'

permissions:
  contents: write

jobs:
  # maintainer note:
  # if the maintainer wants auto-commits, fine â€“ it runs only in the upstream repo.
  # but in forks this would just spam commits and is therefore disabled here.
  php-code-styling:
    if: github.repository == 'Devonab/filament-easy-footer'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.6


      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Fix styling
